import re

APPLICATION_MIME_TO_CATEGORY = {
    "application/pdf": "document",
    "application/rtf": "document",
    "application/msword": "document",
    "application/vnd.ms-word.document.macroenabled.12": "document",
    "application/vnd.ms-word.template.macroenabled.12": "document",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "document",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.template": "document",
    "application/epub+zip": "document",
    "application/vnd.amazon.ebook": "document",
    "application/vnd.oasis.opendocument.text": "document",
    "application/vnd.oasis.opendocument.text-template": "document",
    "application/vnd.oasis.opendocument.text-master": "document",
    "application/vnd.oasis.opendocument.text-web": "document",
    "application/postscript": "document",
    "application/vnd.ms-xpsdocument": "document",

    "application/vnd.ms-excel": "spreadsheet",
    "application/vnd.ms-excel.sheet.binary.macroenabled.12": "spreadsheet",
    "application/vnd.ms-excel.sheet.macroenabled.12": "spreadsheet",
    "application/vnd.ms-excel.template.macroenabled.12": "spreadsheet",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "spreadsheet",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.template": "spreadsheet",
    "application/vnd.oasis.opendocument.spreadsheet": "spreadsheet",
    "application/vnd.oasis.opendocument.spreadsheet-template": "spreadsheet",

    "application/vnd.ms-powerpoint": "presentation",
    "application/vnd.ms-powerpoint.presentation.macroenabled.12": "presentation",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": "presentation",
    "application/vnd.openxmlformats-officedocument.presentationml.slide": "presentation",
    "application/vnd.openxmlformats-officedocument.presentationml.slideshow": "presentation",
    "application/vnd.openxmlformats-officedocument.presentationml.template": "presentation",
    "application/vnd.oasis.opendocument.presentation": "presentation",
    "application/vnd.oasis.opendocument.presentation-template": "presentation",

    "application/zip": "archive",
    "application/x-zip-compressed": "archive",
    "application/gzip": "archive",
    "application/x-gzip": "archive",
    "application/x-bzip": "archive",
    "application/x-bzip2": "archive",
    "application/x-tar": "archive",
    "application/x-7z-compressed": "archive",
    "application/vnd.rar": "archive",
    "application/x-rar-compressed": "archive",
    "application/x-debian-package": "archive",
    "application/vnd.debian.binary-package": "archive",
    "application/x-rpm": "archive",
    "application/x-redhat-package-manager": "archive",

    "application/java-archive": "executable",
    "application/java-vm": "executable",
    "application/x-mach-binary": "executable",
    "application/octet-stream": "executable",
    "application/x-msdownload": "executable",
    "application/x-sh": "executable",
    "application/x-shellscript": "executable",
    "application/vnd.nokia.n-gage.symbian.install": "executable",
    "application/vnd.android.package-archive": "executable",
}

TERM_TO_CATEGORY = {
    "document": "document",
    "microsoft word": "document",
    "opendocument text": "document",
    "apple pages": "document",
    "rich text format": "document",
    "latex document": "document",

    "powerpoint": "presentation",
    "presentation": "presentation",
    "keynote": "presentation",

    "excel": "spreadsheet",
    "spreadsheet": "spreadsheet",
    "apple numbers": "spreadsheet",
    "csv": "spreadsheet",
    "tsv": "spreadsheet",
    "spreadsheetml": "spreadsheet",
    "comma-separated": "spreadsheet",
    "tab-separated": "spreadsheet",

    "archive": "archive",
    "zip": "archive",
    "compress": "archive",
    "tar": "archive",
    "package": "archive",
    "iso": "archive",
    "disc image": "archive",
    "disk image": "archive",

    "executable": "executable",
    "installer": "executable",
    "shell script": "executable",
    "shared object": "executable",
    "mach-o": "executable"
}

TERM_PATTERN = re.compile("|".join(re.escape(k) for k in TERM_TO_CATEGORY), re.IGNORECASE)

EXTENSION_TO_CATEGORY = {
    ".3g2": "audio",
    ".3gp": "audio",
    ".3gpp": "audio",
    ".3gpp2": "audio",
    ".7z": "archive",
    ".a": "executable",
    ".aac": "audio",
    ".adts": "audio",
    ".ai": "document",
    ".aif": "audio",
    ".aifc": "audio",
    ".aiff": "audio",
    ".ass": "audio",
    ".au": "audio",
    ".avi": "video",
    ".avif": "image",
    ".apk": "archive",
    ".app": "executable",
    ".bat": "executable",
    ".bin": "executable",
    ".bmp": "image",
    ".bz2": "archive",
    ".c": "text",
    ".cab": "archive",
    ".css": "text",
    ".csv": "spreadsheet",
    ".cmd": "executable",
    ".command": "executable",
    ".com": "executable",
    ".deb": "archive",
    ".dll": "executable",
    ".doc": "document",
    ".docx": "document",
    ".dot": "document",
    ".dotx": "document",
    ".dmg": "archive",
    ".ear": "archive",
    ".eps": "document",
    ".etx": "text",
    ".exe": "executable",
    ".fods": "spreadsheet",
    ".gif": "image",
    ".gz": "archive",
    ".h": "text",
    ".heic": "image",
    ".heif": "image",
    ".htm": "text",
    ".html": "text",
    ".ico": "image",
    ".iso": "archive",
    ".ipynb": "document",
    ".ief": "image",
    ".jar": "archive",
    ".jpe": "image",
    ".jpeg": "image",
    ".jpg": "image",
    ".json": "text",
    ".ksh": "text",
    ".key": "presentation",
    ".kth": "presentation",
    ".loas": "audio",
    ".lz": "archive",
    ".lzma": "archive",
    ".m1v": "video",
    ".mov": "video",
    ".movie": "video",
    ".mp2": "audio",
    ".mp3": "audio",
    ".mp4": "video",
    ".mpa": "video",
    ".mpe": "video",
    ".mpeg": "video",
    ".mpg": "video",
    ".msi": "executable",
    ".n3": "text",
    ".numbers": "spreadsheet",
    ".o": "executable",
    ".obj": "executable",
    ".opus": "audio",
    ".odp": "presentation",
    ".otp": "presentation",
    ".odt": "document",
    ".ott": "document",
    ".ods": "spreadsheet",
    ".ots": "spreadsheet",
    ".out": "executable",
    ".pages": "document",
    ".pbm": "image",
    ".pdf": "document",
    ".pgm": "image",
    ".pl": "text",
    ".png": "image",
    ".pnm": "image",
    ".pot": "presentation",
    ".potx": "presentation",
    ".ppa": "document",
    ".ppm": "image",
    ".pps": "presentation",
    ".ppsx": "presentation",
    ".ppt": "presentation",
    ".pptx": "presentation",
    ".ps": "document",
    ".ps1": "executable",
    ".pwz": "document",
    ".prezi": "presentation",
    ".pecha": "presentation",
    ".py": "text",
    ".qt": "video",
    ".ra": "audio",
    ".ras": "image",
    ".rar": "archive",
    ".rgb": "image",
    ".rtx": "text",
    ".rtf": "document",
    ".rpm": "archive",
    ".run": "executable",
    ".scr": "executable",
    ".sgm": "text",
    ".sgml": "text",
    ".sh": "executable",
    ".snd": "audio",
    ".so": "executable",
    ".srt": "text",
    ".svg": "image",
    ".sdd": "presentation",
    ".tar": "archive",
    ".tif": "image",
    ".tiff": "image",
    ".tsv": "spreadsheet",
    ".txt": "text",
    ".tex": "document",
    ".tgz": "archive",
    ".vcf": "text",
    ".vtt": "text",
    ".wasm": "executable",
    ".war": "archive",
    ".wav": "audio",
    ".webm": "video",
    ".wiz": "document",
    ".xbm": "image",
    ".xlb": "document",
    ".xls": "spreadsheet",
    ".xlsx": "spreadsheet",
    ".xlsm": "spreadsheet",
    ".xlsb": "spreadsheet",
    ".xlt": "spreadsheet",
    ".xltx": "spreadsheet",
    ".xlstm": "spreadsheet",
    ".xml": "text",
    ".xpm": "image",
    ".xwd": "image",
    ".xz": "archive",
    ".zip": "archive",
    ".z": "archive",
}